apiVersion: v1
kind: Service
metadata:
  name: btcpayserver
  namespace: crypto-demo
spec:
  type: ClusterIP
  selector:
    app: btcpayserver
  ports:
    - name: http
      port: 14142
      targetPort: 14142
